#!/bin/bash

rm .monitor/last-build

clear
tmux clear-history

while true; do
  script -O /dev/null -q -e -c 'cabal build qasm3to2' > .monitor/this-build
  res=$?
  if diff .monitor/this-build .monitor/last-build > /dev/null; then
    sleep 2
    continue
  fi
  mv .monitor/this-build .monitor/last-build
  clear
  tmux clear-history
  if [ "$res" == "0" ]; then
    for F in test-data/*.qasm; do
      echo "$F:"
      cabal run qasm3to2 "$F"
      echo
    done
  else
    cat .monitor/last-build
  fi
  sleep 2
done
