#!/bin/bash

rm .monitor/last-build

if ! ([ -d .monitor ] && [ -f qasm3to2.cabal ]) ; then
  echo "Did not find expected files, are we in the right folder?"
  exit 1
fi

clear
tmux clear-history

while true; do
  script -O /dev/null -q -e -c 'cabal build qasm3to2-testsuite' > .monitor/this-build
  res=$?
  if test -f .monitor/last-build && (diff -q .monitor/this-build .monitor/up-to-date > /dev/null \
      || diff -q .monitor/this-build .monitor/last-build > /dev/null); then
    sleep 15
    continue
  fi
  mv .monitor/this-build .monitor/last-build
  clear
  tmux clear-history
  if [ "$res" == "0" ]; then
    cabal test
    # for F in test-data/*.qasm; do
    #   echo "$F:"
    #   cabal run "$F"
    #   echo
    # done
  else
    cat .monitor/last-build
  fi
  sleep 2
done
